# Generated by Django 2.2.5 on 2019-09-24 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=32)),
                ('teacher_handling_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Teacher')),
            ],
        ),
    ]
