# Generated by Django 2.2.5 on 2019-09-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_question_student_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
