# Generated by Django 2.2.5 on 2019-09-24 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('optionA', models.CharField(max_length=32)),
                ('optionB', models.CharField(max_length=32)),
                ('optionC', models.CharField(max_length=32)),
                ('optionD', models.CharField(max_length=32)),
                ('answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Course')),
            ],
        ),
    ]
